# Secret для хранения секрета OAuth2 клиента Front UI
apiVersion: v1
kind: Secret
metadata:
  name: front-ui-oauth-secret # Имя Secret, на который ссылается Deployment
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
type: Opaque
data:
  # Используйте ваш реальный CLIENT_SECRET, закодированный в Base64.
  # Например, "L9y7QNdc8SqHm0FZkN8pXJkpF2bN7nTf" -> base64(L9y7QNdc8SqHm0FZkN8pXJkpF2bN7nTf)
  CLIENT_SECRET: Lzl5N1FOZGM4U3FIbTBGWmtOOE9tTnpGUW1DNTk2Zg== # Пример Base64-кодирования