server:
  port: 8087

spring:
  application:
    name: notification-service

logging:
  level:
    com.practicum.bank.notification-serivce: DEBUG

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group

kafka:
  topic:
    notifications: notifications