# Secret для хранения пароля PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-db.fullname" . }}-secret # Имя Secret для БД
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
type: Opaque
data:
  # POSTGRES_PASSWORD: пароль (значение "password" в Base64)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=