# Headless Service для StatefulSet PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "postgres-db.selectorLabels" . | nindent 4 }}
  clusterIP: None # Делает Service Headless, необходим для StatefulSet