# Secret для Notification Service
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-oauth-secret
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_SECRET: bm90aWZpY2F0aW9uX3NlcnZpY2Vfc2VjcmV0 # Пример