# ConfigMap для микросервиса Transfer Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}-config
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  # Настройки подключения к БД
  DB_URL: "jdbc:postgresql://{{ printf "%s-postgres-db" .Release.Name }}:5432/accounts_db"
  DB_USERNAME: "postgres"

  # Адрес сервера авторизации Keycloak
  OAUTH_SERVER_URL: "http://{{ printf "%s-oauth-server" .Release.Name }}:8080/realms/bank-realm"

  # Настройки безопасности/OAuth Client Credentials
  OAUTH_CLIENT_ID: "transfer-service-client"