# Secret для хранения секрета OAuth2 клиента Transfer Service
apiVersion: v1
kind: Secret
metadata:
  name: transfer-service-oauth-secret
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Пример Base64-кодирования для CLIENT_SECRET
  CLIENT_SECRET: dHJhbnNmZXJfc2VydmljZV9zZWNyZXQ=