apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k" # Keycloak часто требует увеличенный буфер заголовков
spec:
  ingressClassName: nginx
  rules:
    # 1. Правило для Keycloak (на отдельном поддомене)
    # В браузере открывать: http://keycloak.localhost
    - host: keycloak.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

    # 2. Правила для основного приложения
    # В браузере открывать: http://localhost
    - host: localhost
      http:
        paths:
          - path: /api/accounts
            pathType: Prefix
            backend:
              service:
                name: accounts-service
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: 8088