# Secret для Exchange Generator
apiVersion: v1
kind: Secret
metadata:
  name: exchange-generator-oauth-secret
  labels:
    {{- include "exchange-generator.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_SECRET: Z2VuZXJhdG9yX3NlcnZpY2Vfc2VjcmV0 # Пример