# Secret для хранения пароля администратора Keycloak
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth-server.fullname" . }}-secret
  labels:
    {{- include "oauth-server.labels" . | nindent 4 }}
type: Opaque
data:
  # KEYCLOAK_ADMIN_PASSWORD: admin (значение "admin" в Base64)
  ADMIN_PASSWORD: YWRtaW4=