# Secret для хранения секрета OAuth2 клиента Accounts Service
apiVersion: v1
kind: Secret
metadata:
  name: accounts-service-oauth-secret # Имя Secret
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Пример Base64-кодирования для CLIENT_SECRET
  CLIENT_SECRET: eW91cl9hY2NvdW50c19zZXJ2aWNlX3NlY3JldA==