server:
  port: 8089

spring:
  application:
    name: exchange-generator
  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  level:
    com.practicum.bank.exchange-generator: DEBUG