# Default values for notification-service.
replicaCount: 1

image:
  repository: bank-app/notification-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8086

env:
  DB_USERNAME: postgres
