# Secret для хранения секрета OAuth2 клиента Exchange Service
apiVersion: v1
kind: Secret
metadata:
  name: exchange-service-oauth-secret
  labels:
    {{- include "exchange-service.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_SECRET: ZXhjaGFuZ2Vfc2VydmljZV9zZWNyZXQ=